[project]
name = "larql"
version = "0.1.0"
description = "Lark Parser for SPARQL 1.1"
readme = "README.md"
authors = [
    { name = "Lukas Plank", email = "lupl@tuta.io" }
]
requires-python = ">=3.11"
dependencies = [
    "lark>=1.2.2",
]

[project.scripts]
larql = "larql:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "devtools>=0.12.2",
    "pytest>=8.3.4",
    "rdflib>=7.1.3",
]
